name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  xcode_14_2:
    runs-on: macos-12
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Version
        run: swift --version
      - name: Build
        run: swift build --build-tests
      - name: Test
        run: swift test --enable-code-coverage
      - name: Gather code coverage
        run: xcrun llvm-cov export -format="lcov" .build/debug/AwaitingPackageTests.xctest/Contents/MacOS/AwaitingPackageTests -instr-profile .build/debug/codecov/default.profdata > coverage_report.lcov
      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage_report.lcov

  xcode_13_4:
    runs-on: macos-12
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.4.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Version
        run: swift --version
      - name: Build
        run: swift build --build-tests
      - name: Test
        run: swift test --skip-build

  xcode_13_2_1:
    runs-on: macos-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Version
        run: swift --version
      - name: Build
        run: swift build --build-tests
      - name: Test
        run: swift test --skip-build

  linux_swift_5_6_3:
    runs-on: ubuntu-latest
    container: swift:5.6.3
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Version
        run: swift --version
      - name: Build
        run: swift build --build-tests
      - name: Test
        run: swift test --skip-build

  linux_swift_5_7:
    runs-on: ubuntu-latest
    container: swift:5.7
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Version
        run: swift --version
      - name: Build
        run: swift build --build-tests
      - name: Test
        run: swift test --skip-build